### ISSUE TITLE
Possibility to extract summary values from fitted `scampr` models

### ISSUE THREAD

**Issue by Martin-Jung** [ElliotDovers/scampr#7]
Fitted `scampr` models can be summarized via `summary(mod)`, however opposed to the default behaviour of `summary` for other models like `glm` or similar, the `summary` method for `scampr` only prints the results but does not return them.
This makes it for example impossible to extract z or p-values.

**Test:**
```
 # Get the flora data for one of the species
dat_pa <- flora$pa

# Ensure the "response" variable in each data set shares the same name
dat_pa$presence <- dat_pa$sp1

# Binary Regression
m.bin <- scampr(presence ~ MNT, dat_pa, include.sre = F, model.type = "PA")
# Save summary
ss <- summary(m.bin)
ss
```
> NULL

**Comment by ElliotDovers** [comment]
I've added this capacity (for the fixed effect components since these are the z and p-values displayed) but beware that [Adding Spatially-Correlated Errors Can Mess Up the Fixed Effect You Love](https://www.tandfonline.com/doi/abs/10.1198/tast.2010.10052) and the spatial random effects used in `scampr` can lead to this issue. Note also that standard errors for both fixed, random effects can be found in the model object: `mod$fixed.effects` and `mod$random.effects` (provided the `mod` has been fitted with `se = TRUE`).

Thanks Martin. I'm going to close this issue.
