### ISSUE TITLE
Bug for Intercept only `bias.formula` in IDM models

### ISSUE THREAD

**Issue by Martin-Jung** [ElliotDovers/scampr#8]
When no bias.formula is provided to a model with model.type = "IDM", there is warning that a bias.formula's is strongly recommended (which might be study dependent though). Yet when an Intercept only formula is provided (as instructed) there is an error?

Example:
```
# Get the flora data for one of the species
dat_po <- flora$po$sp1
dat_pa <- flora$pa

# obtain a sample of 10,000 quadrature points for the point process model
set.seed(1)
quad.pts <- flora$quad[sample(1:nrow(flora$quad), 10000, replace = F), ]
set.seed(NULL)

# Attach the quadrature points to the presence-only data
dat_po <- rbind.data.frame(dat_po, quad.pts)

# Ensure the "response" variable in each data set shares the same name
dat_po$presence <- dat_po$pres
dat_pa$presence <- dat_pa$sp1

# Integrated Data Model
m.comb <- scampr(presence ~ MNT, dat_po, 
                 pa.data = dat_pa, include.sre = F, model.type = "IDM", latent.po.biasing = F)
```
This works but the warning:

> In get.TMB.data.input(formula = presence ~ MNT, data = list(x = c(310.305,  :
>   No 'bias.formula' provided. It is strongly recommended that users include an intercept for the PO biasing process with 'bias.formula = ~ 1'
> 

However when as instrcuted a dummy bias.formula with intercept is added, the model bugs out...
```
m.comb <- scampr(presence ~ MNT, dat_po, bias.formula = ~1,
                 pa.data = dat_pa, include.sre = F, model.type = "IDM", latent.po.biasing = F)
```

> Error in get.TMB.data.input(formula = ~1, data = list(x = c(310.305, 294.605,  : 
>   NA values present in (possibly transformed) predictors within the 'bias.formula'
> Check your data (including offset terms) and try again.

**Comment by ElliotDovers** [comment]
Thanks for picking this up Martin. I introduced this bug with my previous fix for the scoping of formulae (late night debugging -> typo). Should be working now. Let me know if you get a chance to try it out and I'll close this off.

Note that the warning regarding the inclusion of the `bias.formula` in the IDM is there because excluding it would effectively be assuming that the presence-only data represent a census of the domain (*i.e.*, all the species presences have been perfectly detected) which is not usually the case for PO data. This type of misspecification would lead to biasing of the shared intercept. Having a separate PO bias intercept gives the IDM a bit more wiggle room (and is even a good idea when `latent.po.biasing = T`).

Thanks again!
